#!/bin/bash
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"
echo "setup script started!"

dotfiles=(
  nvim
  nixpkgs
)

for package in "${dotfiles[@]}"; do
  if [ ! -d "$XDG_CONFIG_HOME"/"$package" ]; then
    echo "(setup script:) installing $package..."
    cp -r $package "$XDG_CONFIG_HOME"/"$package"
  else
    echo "$package already has a dotfile directory"
  fi
done

nix-env -iA nixpkgs.myPackages
touch test.txt
