#!/bin/bash
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"
echo "setup script started!"

dotfiles=(
  nvim
  nixpkgs
  # tmux
)

for package in "${dotfiles[@]}"; do
  if [ ! -d "$XDG_CONFIG_HOME"/"$package" ]; then
    echo "(setup script:) installing $package dotfiles..."
    cp -r $package "$XDG_CONFIG_HOME"/"$package"
  else
    echo "$package already has a dotfile directory"
  fi
done

# setup tpm
# git clone https://github.com/tmux-plugins/tpm "$XDG_CONFIG_HOME"/tmux/plugins/tpm

# symlinks
ln -sf "$PWD/.bashrc" "$HOME"/.bashrc
ln -sf "$PWD/.bash_aliases" "$HOME"/.bash_aliases
ln -sf "$PWD/.terminfo/" "$HOME"/.terminfo/

# install packages from nixpkgs/config.nix
nix-env -iA nixpkgs.myPackages
